In [6]:
import numpy as np
from open3d import *

In [2]:
!ls -lh

total 5.4M
-rw-r--r-- 1 root root   72 May 31 03:40 opem3d.ipynb
-rw-r--r-- 1 root root 5.4M May 31 03:41 sample_table.pcd


In [3]:
print("Testing IO for point cloud ...")
pcd = read_point_cloud("sample_table.pcd")
print(pcd)
write_point_cloud("copy_of_sample_table.pcd", pcd)

Testing IO for point cloud ...
PointCloud with 460400 points.


True

In [4]:
!ls -lh

total 11M
-rw-r--r-- 1 root root 5.3M May 31 03:42 copy_of_sample_table.pcd
-rw-r--r-- 1 root root 1.4K May 31 03:42 opem3d.ipynb
-rw-r--r-- 1 root root 5.4M May 31 03:41 sample_table.pcd


In [7]:
print("Load a ply point cloud, print it, and render it")
pcd = read_point_cloud("sample_table.pcd")
print(pcd)
print(np.asarray(pcd.points))


Load a ply point cloud, print it, and render it
PointCloud with 460400 points.
[[-0.93387002 -0.6825     -1.18649995]
 [-0.93172997 -0.68322998 -1.18780005]
 [-0.92185003 -0.68054003 -1.18309999]
 ...
 [-0.12585001  0.38914001 -1.35699999]
 [-0.14683001  0.36662    -1.27849996]
 [-0.12884     0.37395999 -1.30410004]]


In [8]:
#draw_geometries([pcd])